# Automatic Makefile made by make4js by N.J.M.
export FGLDBPATH=../etc
export FGLRESOURCEPATH=../etc
export DBNAME=../etc/training.db

fgl_obj1 =  \
	 menu.$(4GLOBJ) \
	 lib.$(4GLOBJ) 

fgl_obj2 =  \
	 cust_mnt.$(4GLOBJ) \
	 lib.$(4GLOBJ) \
	 lookup.$(4GLOBJ) \

fgl_frm2 =  \
	 cust_mnt.$(FRMOBJ) \
	 menu.$(FRMOBJ) \

#depend::
#	echo "making depends";  cd lib ; ./link_lib

ARG1=M
ARG2=menu_sg
PRG1=menu.42r
PRG2=cust_mnt.42r

include ./Make_fjs.inc
